### ISSUE TITLE
Find repos using the tf-state-buckets module and bump their version to v0.1.1

### ISSUE THREAD

**Issue by comozo** [harrison-ai/harrison-terraform-module-tf-state-buckets#12]
Stack and env to update
```[tasklist]
### Tasks
- [x] Update network env
- [x] Update shared env
- [x] Update ai stack for harrison-ai-dev
- [x] Update ai stack for harrison-ai-prod
- [x] Update hpc stack for dev
- [x] Update hpc stack for prod
- [x] Update it stack
- [x] Update harrison-infra-aws-organisation
```

**Comment by comozo** [comment]
Need to apply change to Harrison-infra-aws-organisation. PR is ready @schattingh @dcarrion87

**Comment by dcarrion87** [comment]
This issue has been migrated to Jira: https://harrison-ai.atlassian.net/browse/HPI-72
